import Navbar from "./components/layout/navbar";
import Footer from "./components/layout/footer";
import "./globals.css";


export const metadata = {
  title: "Sample",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-mono min-h-screen">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
